spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    org.springframework: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace
